DEFAULT_PRODUCTS = [
    {
        "_id": "prod_hp_laptop",
        "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
        "name": "HP Laptop",
        "description": "A dependable everyday laptop for browsing, work, and entertainment.",
        "category": "Laptop",
        "brand": "HP",
        "price": 600,
        "rating": 5,
        "numRev": 11,
        "stock": 16,
    },
    {
        "_id": "prod_lenovo_laptop",
        "image": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=900&q=80",
        "name": "Lenovo Laptop",
        "description": "A portable laptop with solid performance for daily productivity.",
        "category": "Laptop",
        "brand": "Lenovo",
        "price": 580,
        "rating": 4.5,
        "numRev": 25,
        "stock": 20,
    },
    {
        "_id": "prod_redgear_mouse",
        "image": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80",
        "name": "Mouse",
        "description": "Responsive wired gaming mouse with comfortable grip.",
        "category": "Computer Accessories",
        "brand": "Redgear",
        "price": 350,
        "rating": 3,
        "numRev": 46,
        "stock": 2,
    },
    {
        "_id": "prod_samsung_monitor",
        "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
        "name": "Monitor",
        "description": "Crisp display for workstations, gaming setups, and home desks.",
        "category": "Monitor",
        "brand": "Samsung",
        "price": 270,
        "rating": 4.5,
        "numRev": 17,
        "stock": 9,
    },
    {
        "_id": "prod_oppo_mobile",
        "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
        "name": "Mobile",
        "description": "A modern smartphone for apps, media, and everyday communication.",
        "category": "Mobile & Tablets",
        "brand": "Oppo",
        "price": 300,
        "rating": 2,
        "numRev": 33,
        "stock": 0,
    },
    {
        "_id": "prod_hp_keyboard",
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80",
        "name": "Keyboard",
        "description": "Full-size keyboard with comfortable typing feel.",
        "category": "Computer Accessories",
        "brand": "HP",
        "price": 120,
        "rating": 4,
        "numRev": 20,
        "stock": 50,
    },
    {
        "_id": "prod_boat_earphone",
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80",
        "name": "Earphone",
        "description": "Compact earphones with clear sound and daily comfort.",
        "category": "Earphones",
        "brand": "Boat",
        "price": 90,
        "rating": 5,
        "numRev": 14,
        "stock": 4,
    },
    {
        "_id": "prod_apple_mouse",
        "image": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80",
        "name": "Apple Mouse",
        "description": "Minimal wireless mouse with a smooth, modern profile.",
        "category": "Computer Accessories",
        "brand": "Apple",
        "price": 500,
        "rating": 5,
        "numRev": 180,
        "stock": 80,
    },
    {
        "_id": "prod_lg_ultrawide_monitor",
        "image": "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=900&q=80",
        "name": "Ultrawide Monitor",
        "description": "Wide display for multitasking and immersive desktop setups.",
        "category": "Monitor",
        "brand": "LG",
        "price": 320,
        "rating": 4,
        "numRev": 60,
        "stock": 14,
    },
    {
        "_id": "prod_tiitan_earphone",
        "image": "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
        "name": "Tiitan Earphone",
        "description": "Lightweight earphones tuned for music, calls, and travel.",
        "category": "Earphones",
        "brand": "Tiitan",
        "price": 80,
        "rating": 5,
        "numRev": 14,
        "stock": 160,
    },
]
